// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import com.model.Admin;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class CustomAdminDetails_isAccountNonExpired_1875f479de_Test {

    private Admin admin;

    @BeforeEach
    public void setUp() {
        admin = new Admin();
    }

    @Test
    public void testIsAccountNonExpired() {
        // As method always return true, so we just asserting it with true
        assertTrue(admin.isAccountNonExpired());
    }

    @Test
    public void testIsAccountNotExpired() {
        // Negation of the previous case just for cover all scenarios
        assertFalse(!admin.isAccountNonExpired());
    }
}
