// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import com.model.User;
import com.custom.CustomUserDetails;

@RunWith(MockitoJUnitRunner.class)
public class CustomUserDetails_getUsername_0a6d3fd936_Test {
    
    @InjectMocks
    CustomUserDetails customUserDetails;
    
    @Mock
    User user;
    
    @Test
    public void testGetUsername_Success() {
        String userEmail = "test@example.com";
        
        // TODO: change the value of userEmail as per the requirement 
        
        when(user.getEmail()).thenReturn(userEmail);
        String username = customUserDetails.getUsername();
        
        assertEquals(userEmail, username);
    }
    
    @Test
    public void testGetUsername_Null() { 
        when(user.getEmail()).thenReturn(null);
        String username = customUserDetails.getUsername();
        
        assertEquals(null, username);
    }
}
