// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import com.model.CustomUserDetails;

public class CustomUserDetails_isAccountNonExpired_1875f479de_Test {

    @InjectMocks
    private CustomUserDetails customUserDetails;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(customUserDetails);
    }
    
    @Test
    public void testIsAccountNonExpired() {
        assertTrue(customUserDetails.isAccountNonExpired());
    }

    @Test
    public void testIsAccountExpired() {
        assertFalse(!customUserDetails.isAccountNonExpired());
    }
}
