// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import com.model.Admin;

public class CustomAdminDetails_getUsername_0a6d3fd936_Test {

    @Mock
    private Admin adm;
  
    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void getUsername_WhenAdminNameIsValid() {
        when(adm.getName()).thenReturn("TestName");
        String username = adm.getName();
        assertEquals("TestName", username, "Admin name should match the expected name");
    }

    @Test
    public void getUsername_WhenAdminNameIsEmpty() {
        when(adm.getName()).thenReturn("");
        String username = adm.getName();
        assertEquals("", username, "Admin name should match the expected name when admin name is empty");
    }
}
