// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;
import com.model.CustomAdminDetails;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class CustomAdminDetails_isEnabled_6732b09672_Test {

    private CustomAdminDetails customAdminDetails;

    @BeforeEach
    public void setUp() {
        customAdminDetails = new CustomAdminDetails();
    }

    @Test
    public void testIsEnabled() {
        boolean result = customAdminDetails.isEnabled();
        assertTrue(result, "isEnabled must always return true");
    }
}
