// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

import com.model.Admin;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class CustomAdminDetails_CustomAdminDetails_6bc92bc701_Test {

    private CustomAdminDetails customAdminDetails;
    private Admin mockAdmin;

    @BeforeEach
    public void setUp() {
        mockAdmin = mock(Admin.class);
    }
    
    @Test
    public void testCustomAdminDetails() {
        customAdminDetails = new CustomAdminDetails(mockAdmin);
        assertEquals(mockAdmin, customAdminDetails.getAdmin(), "admin assigned during object creation should be equal to output of getAdmin method");
    }

    @Test
    public void testCustomAdminDetails_withNullAdmin() {
        customAdminDetails = new CustomAdminDetails(null);
        
        // TODO: Change expected to null after enabling the null check in CustomAdminDetails constructor
        assertEquals(null, customAdminDetails.getAdmin(), "When null admin is passed, getAdmin method should return null");
    }    
}
