// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import com.model.Admin;

@ExtendWith(MockitoExtension.class)
public class CustomAdminDetails_getPassword_ec5cf08305_Test {

    @InjectMocks
    private Admin admin;

    @Mock
    private CustomAdminDetails customAdminDetails;

    //Test case for when the getPassword method returns the correct password
    @Test
    public void testGetPasswordWhenCorrectPassword() {
        String expectedPassword = "correctPassword";
        admin.setPassword(expectedPassword);

        when(customAdminDetails.getPassword()).thenReturn(admin.getPassword());

        assertEquals(expectedPassword, customAdminDetails.getPassword());
    }

    //Test case for when the getPassword method returns null
    @Test
    public void testGetPasswordWhenNull() {
        String expectedPassword = null;
        admin.setPassword(expectedPassword);

        when(customAdminDetails.getPassword()).thenReturn(admin.getPassword());

        assertEquals(expectedPassword, customAdminDetails.getPassword());
    }

}
