// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.List;

import com.model.Role;
import com.model.User;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class CustomUserDetails_CustomUserDetails_6153a0c4b2_Test {
    private User user;

    @Before
    public void setUp() throws Exception {
        user = Mockito.mock(User.class);
    }

    @Test
    public void testCustomUserDetails_ConstructorWithValidUser() {
        CustomUserDetails customUserDetails = new CustomUserDetails(user);
        assertEquals(user, customUserDetails.getUser());
    }

    @Test(expected = NullPointerException.class)
    public void testCustomUserDetails_ConstructorWithNullUser() {
        CustomUserDetails customUserDetails = new CustomUserDetails(null);
    }

}
