// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.test.mock.mockito.SpyBean;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class CustomUserDetails_isCredentialsNonExpired_8b4fc66884_Test {

    @SpyBean
    private CustomUserDetails customUserDetails;

    @BeforeEach
    void setUp() {
        customUserDetails = new CustomUserDetails();
    }

    @Test
    void testIsCredentialsNonExpired() {
        boolean result = customUserDetails.isCredentialsNonExpired();
        assertEquals(true, result);
    }

    @Test
    void testIsCredentialsExpired() {
        boolean result = customUserDetails.isCredentialsNonExpired();
        assertEquals(false, !result);
    }

}
