// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import com.model.*;

public class CustomUserDetails_isAccountNonLocked_f7b514125a_Test {

    private CustomUserDetails customUserDetails;

    @BeforeEach
    public void setUp() {
        customUserDetails = new CustomUserDetails();
    }

    // Testing the non locking of user account
    @Test
    public void testIsAccountNonLocked() {

        boolean isAccountNonLocked = customUserDetails.isAccountNonLocked();
        assertEquals(true, isAccountNonLocked, "Account should be non-locked");
    }

    @Test
    public void testIsAccountNonLockedFailure() {

        // TODO: Simulate a scenario where the account is locked
        // For example, use a setter method to lock the account if it's available like customUserDetails.setAccountNonLocked(false);

        boolean isAccountNonLocked = customUserDetails.isAccountNonLocked();
        assertEquals(false, isAccountNonLocked, "Account should be locked");
    }
}
