// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import org.junit.Assert;
import org.junit.Test;

public class CustomAdminDetails_isCredentialsNonExpired_8b4fc66884_Test {

    @Test
    public void testIsCredentialsNonExpired_True() {
        // Setup
        final CustomAdminDetails customAdminDetails = Mockito.mock(CustomAdminDetails.class);
        Mockito.when(customAdminDetails.isCredentialsNonExpired()).thenReturn(true);

        // Test
        final boolean result = customAdminDetails.isCredentialsNonExpired();

        // Assert
        Assert.assertEquals("The credentials are not expired", true, result);
    }

    @Test 
    public void testIsCredentialsNonExpired_False() {
        // Setup
        final CustomAdminDetails customAdminDetails = Mockito.mock(CustomAdminDetails.class);
        Mockito.when(customAdminDetails.isCredentialsNonExpired()).thenReturn(false);

        // Test
        final boolean result = customAdminDetails.isCredentialsNonExpired();

        // Assert
        Assert.assertEquals("The credentials are expired", false, result);
    }
}
