// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import com.model.User;

public class CustomUserDetails_isEnabled_6732b09672_Test {
  
  @Test
  public void testIsEnabledSuccess() {
    User user = new User();
    Assertions.assertTrue(user.isEnabled(), "Expected isEnabled() to return true, but it didn't");
  }
  
  @Test
  public void testIsEnabledFailure() {
    User user = new User();
    Assertions.assertFalse(!user.isEnabled(), "Expected isEnabled() to return true, not false");
  }
}
