// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.config;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.mockito.Mockito.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class CustomAdminDetails_isAccountNonLocked_f7b514125a_Test {

    @Autowired
    private Admin mockAdmin;

    @BeforeEach
    public void setUp() {
        mockAdmin = mock(Admin.class);
    }

    @Test
    public void testAdminAccount_IsNonLocked() {
        when(mockAdmin.isAccountNonLocked()).thenReturn(true);
        assertTrue(mockAdmin.isAccountNonLocked(), "Account is expected to be Non-locked");
    }

    @Test
    public void testAdminAccount_IsLocked() {
        when(mockAdmin.isAccountNonLocked()).thenReturn(false);
        assertFalse(mockAdmin.isAccountNonLocked(), "Account is expected to be locked");
    }
}
