// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import com.model.Admin;
import com.model.Role;
import com.service.AdminService;
import com.service.RoleService;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class VotingAppApplication_run_6618197254_Test {

    @Autowired
    private AdminService admserv;

    @Autowired
    private RoleService roleserv;

    @Test
    public void testRoleAddsCorrectly() throws Exception {
        Role role1 = new Role();
        role1.setId(1);
        role1.setName("ROLE_ADMIN");

        RoleService mockRoleServ = mock(RoleService.class);

        when(mockRoleServ.addRole(role1)).thenReturn(role1);
        assertEquals(role1, mockRoleServ.addRole(role1));
    }

    @Test
    public void testAdminAddsCorrectly() throws Exception {
        Admin a1 = new Admin();
        a1.setId(1);
        a1.setName("admin");
        a1.setPassword("admin");

        List<Role> r = new ArrayList<>();
        r.add(roleserv.getRoleByName("ROLE_ADMIN"));
        a1.setRoles(r);

        AdminService mockAdminServ = mock(AdminService.class);

        when(mockAdminServ.addAdmin(a1)).thenReturn(a1);
        assertEquals(a1, mockAdminServ.addAdmin(a1));
    }
}
