// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.Arrays;
import java.util.List;

public class Admin_Admin_ddc0adaa15_Test {

	//Test case for successful admin creation
	@Test
	public void testAdminCreationSuccess() {
		
		Role role1 = new Role(1, "ROLE_ADMIN");
		Role role2 = new Role(2, "ROLE_USER");
		
		List<Role> roles = Arrays.asList(role1, role2);
		
		Admin admin = new Admin(1, "admin", "password123", roles);
		
		assertEquals(1, admin.getId());
		assertEquals("admin", admin.getName());
		assertEquals("password123", admin.getPassword());
		assertEquals(roles, admin.getRoles());
	}
	
	//Test case for checking if admin creation is unsuccessful when invalid data is passed
	@Test
	public void testAdminCreationFailure() {
		
		Role role1 = new Role(1, "ROLE_ADMIN");
		Role role2 = new Role(2, "ROLE_USER");
		
		List<Role> roles = Arrays.asList(role1, role2);
		
		Admin admin = new Admin(-1, null, "", roles);
		
		assertEquals(-1, admin.getId());
		assertEquals(null, admin.getName());
		assertEquals("", admin.getPassword());
		assertEquals(roles, admin.getRoles());
	}

} //Admin_Admin_ddc0adaa15_Test
