// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.List;

public class Admin_setRoles_4ef6a0a348_Test {

  Admin admin;

  @Mock
  List<Role> roles;

  @BeforeEach
  public void setUp() throws Exception {
    MockitoAnnotations.initMocks(this);
    admin = new Admin();
  }

  @Test
  public void testSetRoles_Success() {
    List<Role> roles = new ArrayList<>();
    Role role = new Role();
    role.setId(1);
    role.setRole("Admin");
    roles.add(role);
    admin.setRoles(roles);
    assertEquals(roles, admin.getRoles());
  }

  @Test
  public void testSetRoles_Null() {
    admin.setRoles(null);
    assertEquals(null, admin.getRoles());
  }
}
