// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Admin_toString_ceffa8036e_Test {

    @Mock
    private Admin admin;
    private String name = "Test";
    private String password = "Test123";
    private List<Role> roles = new ArrayList<>();
    
    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        Role role = new Role();
        role.setId(1);
        role.setName("ROLE_ADMIN");
        roles.add(role);
        admin.setId(1);
        admin.setName(name);
        admin.setPassword(password);
        admin.setRoles(roles);
    }
    
    @Test
    public void testToStringSuccess() {
        String expected = "Admin [id=1, name=Test, password=Test123, roles=[Role [id=1, name=ROLE_ADMIN]]]";
        String actual = admin.toString();
        assertEquals(expected, actual);
    }
    
    @Test
    public void testToStringFailure() {
        String expected = "Admin [id=1, name=Test, password=Test123, roles=[]]";
        String actual = admin.toString();
        assertNotEquals(expected, actual);
    }
}
