// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.beans.factory.annotation.Autowired;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Admin_setPassword_19d13444f4_Test {

    @Autowired
    Admin admin;

    @MockBean
    passwordEncoder passwordEncoder;

    @Test
    public void testSetPasswordSuccess() {
        String password = "userpassword";
        admin.setPassword(password);
        Assertions.assertEquals(password, admin.getPassword(), "Expected and actual password do not match");
    }

    @Test
    public void testSetPasswordFailure() {
        String password = null; // TODO: change the password here
        Assertions.assertThrows(NullPointerException.class, () -> admin.setPassword(password), "Expected NullPointerException to be thrown");
    }
  
}
