// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
class Admin_getPassword_ec5cf08305_Test {
    
    @MockBean
    private Admin admin;

    @Test
    public void testGetPassword_success() {
        String expectedPassword = "password123"; 
        Mockito.when(admin.getPassword()).thenReturn(expectedPassword);

        String actualPassword = admin.getPassword();
        
        assertEquals(expectedPassword, actualPassword, "Password should match expected value");
    }

    @Test
    public void testGetPassword_failure() {
        String expectedPassword = "wrongPassword";
        Mockito.when(admin.getPassword()).thenReturn("password123");

        String actualPassword = admin.getPassword();
        
        assertNotEquals(expectedPassword, actualPassword, "Password should not match incorrect expected value");  
    }
}
