// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;


public class Admin_setName_5d23a892d9_Test {

    @InjectMocks
    Admin admin;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void setName_success(){
        String expectedName = "John Doe";
        admin.setName(expectedName);
        assertEquals(expectedName, admin.getName(), "The name does not set correctly.");
    }
    
    @Test
    public void setName_null(){
        admin.setName(null);
        assertEquals(null, admin.getName(), "The name is not set as null");
    }
    
    @Test 
    public void setName_emptyString() {
        // TODO: User is supposed to change the name according to their requirements.
        String expectedName = "";
        admin.setName(expectedName);
        assertEquals(expectedName, admin.getName(), "The name is not set as empty string.");
    }
    
    @Test 
    public void setName_withSpaces() {
        // TODO: User is supposed to change the name according to their requirements.
        String expectedName = "   John Doe  ";
        admin.setName(expectedName);
        assertEquals(expectedName.trim(), admin.getName(), "The name is not trimmed.");
    }
}
