// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import com.model.Role;

public class Admin_getRoles_dd524a1aa8_Test {

    @Test
    public void testGetRoles_ValidRoleList() {
        Admin admin = new Admin();
        List<Role> roleList = new ArrayList<>();
        Role role1 = new Role();
        role1.setRoleName("Admin");
        roleList.add(role1);

        Role role2 = new Role();
        role2.setRoleName("User");
        roleList.add(role2);
        
        admin.setRoles(roleList);
        List<Role> rolesResult = admin.getRoles();
        assertEquals(2, rolesResult.size());
        assertEquals("Admin", rolesResult.get(0).getRoleName());
        assertEquals("User", rolesResult.get(1).getRoleName());
    }

    @Test
    public void testGetRoles_EmptyRoleList() {
        Admin admin = new Admin();
        List<Role> roleList = new ArrayList<>();
        admin.setRoles(roleList);
        List<Role> rolesResult = admin.getRoles();
        assertEquals(0, rolesResult.size());
    }
}
