// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
public class Admin_getId_92e05748b6_Test {

	@Test
	public void testGetId_Success() {
		Admin admin = new Admin();
		admin.setId(100);

		// invoke the actual method
		int actualId = admin.getId();

		// assert the value
		assertThat(actualId).isEqualTo(100);
	}

	@Test
	public void testGetId_Failure() {
		Admin admin = new Admin();
		admin.setId(200);

		// invoke the actual method
		int actualId = admin.getId();

		// assert the value
		assertThat(actualId).isNotEqualTo(100);
	}
}
