// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.jupiter.api.Assertions.assertEquals;


@RunWith(SpringRunner.class)
@SpringBootTest
public class Admin_setId_17ddd86313_Test {

    private Admin admin;

    @BeforeEach
    public void setUp() {
        admin = new Admin();
    }

    @Test
    public void testSetIdSuccess() {
        admin.setId(100);
        assertEquals(100, admin.getId(), "Admin id should be set to 100");
    }

    @Test
    public void testSetIdFailure() {
        admin.setId(-1);
        assertNotEquals(-1, admin.getId(), "Admin id should not be negative");
    }
}
