// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.Assert.assertEquals;

public class Candidate_getId_92e05748b6_Test {

    @InjectMocks
    Candidate candidate;

    @Before
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetId_Success() {
        int expectedId = 123;
        candidate.setId(expectedId);
        assertEquals(expectedId, candidate.getId());
    }
  
    @Test
    public void testGetId_Zero() {
        int expectedId = 0;
        candidate.setId(expectedId);
        assertEquals(expectedId, candidate.getId());
    }
}
