// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
public class Candidate_setId_17ddd86313_Test {

	private Candidate candidate;

	@BeforeEach
	public void setup() {
		candidate = new Candidate();
	}

	@Test
	public void setId_ValidId_ReturnsTrue() {
		int expectedId = 5;
		candidate.setId(expectedId);
		assertThat(candidate.getId()).isEqualTo(expectedId);
	}

	@Test
	public void setId_NegativeId_ThrowsException() {
		int invalidId = -1;
		try {
			candidate.setId(invalidId);
		} catch (IllegalArgumentException e) {
			assertThat(e.getMessage()).isEqualTo("Id cannot be negative");
		}
	}
}
