// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Candidate_setCandidate2_6ecd8693ac_Test {

    private Candidate candidate;

    @BeforeEach
    public void setUp() {
        candidate = new Candidate();
    }

    @Test
    public void testSetCandidate2_NormalInput() {
        String expectedCandidate2 = "John Doe";
        candidate.setCandidate2(expectedCandidate2);
        assertEquals(expectedCandidate2, candidate.getCandidate2());
    }

    @Test
    public void testSetCandidate2_EmptyString() {
        String expectedCandidate2 = "";
        candidate.setCandidate2(expectedCandidate2);
        assertEquals(expectedCandidate2, candidate.getCandidate2());
    }
}
