// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.jupiter.api.Assertions.assertEquals;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Candidate_getCandidate2_6fd06ef279_Test {

    @InjectMocks
    private Candidate candidate;

    @BeforeEach
    public void setUp(){
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetCandidate2Succeed() {
        candidate.setCandidate2("Successful Candidate");
        String result = candidate.getCandidate2();
        assertEquals("Successful Candidate", result, "Candidate2 should be 'Successful Candidate'");
    }

    @Test
    public void testGetCandidate2Failed() {
        candidate.setCandidate2("Failed Candidate");
        String result = candidate.getCandidate2();
        assertEquals("Failed Candidate", result, "Candidate2 should be 'Failed Candidate'");
    }

}
