// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Role_getId_92e05748b6_Test {

    @Test
    public void testGetIdSuccess() {
        Role role = new Role();
        role.setId(10);
        Assert.assertEquals(10, role.getId());
    }

    @Test
    public void testGetIdFailure() {
        Role role = new Role();
        role.setId(20);
        Assert.assertNotEquals(10, role.getId());
    }
}
