// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.Arrays;
import java.util.List;

// Assuming User and Admin are entities present in your codebase

public class Role_toString_ceffa8036e_Test {

    @InjectMocks
    Role role;

    @Mock
    User user;

    @Mock
    Admin admin;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testToString_NoUsersNoAdmins() {
        role.setId(1);
        role.setName("Role1");
        String expectedString = "Role [id=1, name=Role1, users=null, admins=null]";
        assertEquals(expectedString, role.toString());
    }

    @Test
    public void testToString_WithUsersNoAdmins() {
        role.setId(2);
        role.setName("Role2");
        List<User> users = Arrays.asList(user); // TODO: Set actual user data
        role.setUsers(users);
        String expectedString = "Role [id=2, name=Role2, users=" + users + ", admins=null]";
        assertEquals(expectedString, role.toString());
    }

    @Test
    public void testToString_NoUsersWithAdmins() {
        role.setId(3);
        role.setName("Role3");
        List<Admin> admins = Arrays.asList(admin); // TODO: Set actual admin data
        role.setAdmins(admins);
        String expectedString = "Role [id=3, name=Role3, users=null, admins=" + admins + "]";
        assertEquals(expectedString, role.toString());
    }

    @Test
    public void testToString_WithUsersWithAdmins() {
        role.setId(4);
        role.setName("Role4");
        List<User> users = Arrays.asList(user); // TODO: Set actual user data
        role.setUsers(users);
        List<Admin> admins = Arrays.asList(admin); // TODO: Set actual admin data
        role.setAdmins(admins);
        String expectedString = "Role [id=4, name=Role4, users=" + users + ", admins=" + admins + "]";
        assertEquals(expectedString, role.toString());
    }
}
