// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.Arrays;
import java.util.List;

public class Role_getUsers_20138e9965_Test {

    @InjectMocks
    Role role;
    
    @Mock
    List<User> users; 

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetUsers_Success() {
        User user1 = new User();
        User user2 = new User();
        when(users.get(0)).thenReturn(user1);
        when(users.get(1)).thenReturn(user2);
        role.setUsers(users);
        List<User> userList = role.getUsers();
        assertEquals(user1, userList.get(0));
        assertEquals(user2, userList.get(1));
    }
    
    @Test
    public void testGetUsers_Failure() {
        when(users.get(0)).thenReturn(null);
        role.setUsers(users);
        List<User> userList = role.getUsers();
        assertEquals(null, userList.get(0));
    }

}
