// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Role_setId_17ddd86313_Test {

    @InjectMocks
    Role role;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetIdSuccess() {
        int expectedId = 5;
        role.setId(expectedId);
        assertEquals(expectedId, role.getId(), "The expected Id does not match the actual Id");
    }

    @Test
    public void testSetIdNegative() {
        int expectedId = -1;
        role.setId(expectedId);
        assertEquals(expectedId, role.getId(), "The expected Id does not match the actual Id");
    }
}
