// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import static org.junit.Assert.assertEquals;

import java.util.Arrays;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;

public class Role_getAdmins_a7babdc2bd_Test {

    @InjectMocks
    Role role;

    @Mock
    List<Admin> admins;
    
    @Before
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetAdmins_returnsAdminList() {
        Admin admin1 = new Admin();
        Admin admin2 = new Admin();

        List<Admin> adminList = Arrays.asList(admin1, admin2);
        Mockito.when(role.getAdmins()).thenReturn(adminList);

        List<Admin> result = role.getAdmins();
        assertEquals(adminList, result);
    }

    @Test
    public void testGetAdmins_returnsNull() {
        Mockito.when(role.getAdmins()).thenReturn(null);
        
        List<Admin> result = role.getAdmins();
        assertEquals(null, result);
    }
}
