// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Role_getName_8400ac6fb7_Test {

    @Test
    public void testGetName() {
        Role role = new Role();
        role.setName("admin");
        Assertions.assertEquals("admin", role.getName());
    }

    @Test
    public void testGetNameWithNull() {
        Role role = new Role();
        role.setName(null);
        Assertions.assertNull(role.getName());
    }
}
