// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@SpringBootTest
@RunWith(SpringRunner.class)
public class Role_setName_5d23a892d9_Test {
    private Role role = new Role();

    @Test
    public void testSetName_WithValidName() {
        String expectedName = "Admin";
        role.setName(expectedName);
        String actualName = role.getName();
        Assert.assertEquals("Valid name did not set correctly", expectedName, actualName);
    }

    @Test
    public void testSetName_WithEmptyString() {
        String expectedName = "";
        role.setName(expectedName);
        String actualName = role.getName();
        Assert.assertEquals("Empty name did not set correctly", expectedName, actualName);
    }

    @Test(expected = NullPointerException.class)
    public void testSetName_WithNull() {
        String expectedName = null;
        role.setName(expectedName);
        String actualName = role.getName();
        Assert.assertEquals("Null name did not set correctly", expectedName, actualName);
    }

}
