// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.util.ArrayList;
import java.util.List;

public class Role_Role_0e7602478c_Test {
    
    private List<User> users;
    private List<Admin> admins;
    
    @BeforeEach
    public void setUp() {
        users = new ArrayList<>();
        users.add(Mockito.mock(User.class));
        admins = new ArrayList<>();
        admins.add(Mockito.mock(Admin.class));
    }

    @Test
    public void testRoleCreationSuccess() {
        Role role = new Role(1, "role1", users, admins);

        assertEquals(1, role.getId());
        assertEquals("role1", role.getName());
        assertEquals(users, role.getUsers());
        assertEquals(admins, role.getAdmins());
    }

    @Test
    public void testRoleCreationFailure() {
        Role role = new Role(0, null, users, admins);

        assertEquals(0, role.getId());
        assertEquals(null, role.getName());
        assertEquals(users, role.getUsers());
        assertEquals(admins, role.getAdmins());
    }
}
