// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Role_Role_ec1b84f490_Test {
    
    @Test
    public void testRoleConstructor() {
        Role role = new Role();
        Assert.assertNotNull(role);
    }

    @Test
    public void testRoleValues() {
        Role role = new Role();
        
        Assert.assertNull(role.getId());
        Assert.assertNull(role.getName());
        Assert.assertNull(role.getUsers());
    }
}
