// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.Before;
import org.junit.Test;

public class User_getRoles_dd524a1aa8_Test {

    private User user;

    @Before
    public void setUp() {
        user = new User();
    }

    @Test
    public void testGetRoles_WhenNoRolesAssigned_ReturnsNull() {
        assertNull(user.getRoles());
    }

    @Test
    public void testGetRoles_WhenRolesAssigned_ReturnsRoles() {
        Role role1 = new Role();
        role1.setName("User");

        Role role2 = new Role();
        role2.setName("Admin");

        List<Role> givenRoles = new ArrayList<>(Arrays.asList(role1, role2));
        user.setRoles(givenRoles);

        List<Role> receivedRoles = user.getRoles();
        assertEquals(givenRoles, receivedRoles);
    }

}
