// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class User_setEmail_d1f6d493ae_Test {

	User user;

	@BeforeEach
	public void setUp() {
		user = new User();
	}

	@Test
	public void testSetEmail_ValidEmail() {
		String expectedEmail = "test@example.com";
		user.setEmail(expectedEmail);
		assertEquals(expectedEmail, user.email);
	}

	@Test
	public void testSetEmail_NullEmail() {
		String expectedEmail = null;
		user.setEmail(expectedEmail);
		assertEquals(expectedEmail, user.email);
	}
}
