// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.Arrays;

@RunWith(SpringRunner.class)
@SpringBootTest
public class User_toString_ceffa8036e_Test {

    @Test
    public void testToString() {
        Role role1 = new Role("admin");
        Role role2 = new Role("user");
        User user = new User();
        user.setId(1);
        user.setName("John");
        user.setPassword("password");
        user.setEmail("john@example.com");
        user.setPhone("1234567890");
        user.setRoles(Arrays.asList(role1, role2));

        String expectedToString = "User [id=1, name=John, password=password," +
                                  " email=john@example.com, phone=1234567890," +
                                  " roles=[Role [name=admin], Role [name=user]]]";
        Assert.assertEquals(expectedToString, user.toString());
    }

    @Test
    public void testToStringWithNoRoles() {
        User user = new User();
        user.setId(1);
        user.setName("John");
        user.setPassword("password");
        user.setEmail("john@example.com");
        user.setPhone("1234567890");

        String expectedToString = "User [id=1, name=John, password=password," +
                                  " email=john@example.com, phone=1234567890," +
                                  " roles=null]";
        Assert.assertEquals(expectedToString, user.toString());
    }
}
