// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class User_getId_92e05748b6_Test {

    @InjectMocks
    private User mockUser;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        mockUser.setId(1);
    }

    @Test
    public void testGetId_Success() {
        int expected = 1;
        int actual = mockUser.getId();

        assertEquals(expected, actual);
    }

    @Test
    public void testGetId_Failure() {
        int unexpected = 2;
        int actual = mockUser.getId();

        assertNotEquals(unexpected, actual);
    }
}
