// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class User_setPhone_0adff8dec5_Test {

    private User user;
    
    @Before
    public void setUp() {
        user = new User();
    }
    
    @Test
    public void testSetPhoneSuccess() {
        int phone = 1234567890;
        user.setPhone(phone);
        assertEquals(phone, user.getPhone());
    }

    @Test
    public void testSetPhoneZero() {
        int phone = 0;
        user.setPhone(phone);
        assertEquals(phone, user.getPhone());
    }
}
