// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.util.Assert;

@SpringBootTest
public class User_setName_5d23a892d9_Test {

    @Mock
    private User user;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        user = new User();
    }

    @Test
    public void testSetNameSuccess() {
        String expectedName = "Test User";

        user.setName(expectedName);
        Mockito.verify(user, Mockito.times(1)).setName(expectedName);
        Assert.isTrue(user.getName() == expectedName, "Names should match");
    }

    @Test
    public void testSetNameFailure() {
        String expectedName = null;

        user.setName(expectedName);
        Mockito.verify(user, Mockito.times(1)).setName(expectedName);
        Assert.isTrue(user.getName()== null, "Name should be null");
    }
}
