// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

import java.util.ArrayList;
import java.util.List;

public class User_setRoles_4ef6a0a348_Test {

    @Mock
    List<Role> mockRoles;

    @InjectMocks
    User user;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetRoles() {
        Role role1 = new Role("Admin");
        Role role2 = new Role("Manager");
        List<Role> roles = new ArrayList<>();
        roles.add(role1);
        roles.add(role2);
        user.setRoles(roles);
        assertEquals(roles, user.getRoles());
    }

    @Test
    public void testSetRolesNull() {
        user.setRoles(null);
        assertEquals(null, user.getRoles());
    }
}
