// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import com.model.Role;
import com.model.User;

public class User_User_b7b6575d02_Test {

   private User user;

   @BeforeEach
   public void setup() {
       List<Role> roles = Arrays.asList(new Role("Admin"), new Role("User"));
       user = new User("John Doe", "password", "johndoe@gmail.com", 1234567890, roles);
   }

   @Test
   public void testUserName() {
       String expected = "John Doe";
       String actual = user.getName();
       assertEquals(expected, actual, "The expected output does not match the actual output");
   }

   @Test
   public void testUserPassword() {
       String expected = "password";
       String actual = user.getPassword();
       assertEquals(expected, actual, "The expected output does not match the actual output");
   }

   @Test
   public void testUserEmail() {
       String expected = "johndoe@gmail.com";
       String actual = user.getEmail();
       assertEquals(expected, actual, "The expected output does not match the actual output");
   }

   @Test
   public void testUserPhone() {
       int expected = 1234567890;
       int actual = user.getPhone();
       assertEquals(expected, actual, "The expected output does not match the actual output");
   }

   @Test
   public void testUserRoles() {
       List<Role> expected = Arrays.asList(new Role("Admin"), new Role("User"));
       List<Role> actual = user.getRoles();
       assertEquals(expected, actual, "The expected output does not match the actual output");
   }
}
