// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.assertEquals;

import com.model.Role;
import com.model.User;

import java.util.Arrays;
import java.util.List;


@RunWith(SpringRunner.class)
@SpringBootTest
public class User_User_58418fc4be_Test {
	
    @Test
    public void testUserCreation() {
        Role roleAdmin = new Role(1, "admin");
        List<Role> roles = Arrays.asList(roleAdmin);
        User user = new User(1, "John Doe", "password123", "johndoe@gmail.com", 1234567890, roles);

        assertEquals(1, user.getId());
        assertEquals("John Doe", user.getName());
        assertEquals("password123", user.getPassword());
        assertEquals("johndoe@gmail.com", user.getEmail());
        assertEquals(1234567890, user.getPhone());
        assertEquals(roles, user.getRoles());
    }

    @Test
    public void testUserCreationNoRoles() {
        User user = new User(2, "Jane Smith", "password456", "janesmith@gmail.com", 0987654321, null);
        
        assertEquals(2, user.getId());
        assertEquals("Jane Smith", user.getName());
        assertEquals("password456", user.getPassword());
        assertEquals("janesmith@gmail.com", user.getEmail());
        assertEquals(0987654321, user.getPhone());
        assertEquals(null, user.getRoles());
    }
}
