// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class User_getName_8400ac6fb7_Test {

    private User userTest;

    @BeforeEach
    public void setUp() {
        userTest = mock(User.class);
    }
  
    @Test
    public void testNameWhenNameIsSet() {
        String expectedName = "TestUser";

        when(userTest.getName()).thenReturn(expectedName);
        String actualName = userTest.getName();

        assertEquals(expectedName, actualName, "Returned name should match the expected name");
    }
  
    @Test
    public void testNameWhenNameIsNotSet() {

        when(userTest.getName()).thenReturn(null);
        String actualName = userTest.getName();

        assertEquals(null, actualName, "Returned name should be null as no name is set");
    }
}
